name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  openabe-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build openabe-dev
      run: docker build -t nyub:openabe-dev images/openabe-dev
    - name: Build openabe-tool
      run: docker build -t nyub:openabe-tool images/openabe-tool
